{
    'name': 'JIL CRM',
    'version': '2.0',
    'category': 'Sales/CRM',
    'summary': 'JIL CRM v2.0 — Enterprise Odoo CRM with Lead Management, Sales Pipeline, AI Chatbot, Booking, Projects, Automation, Analytics & Sage 100 ERP Connector',
    'description': 'Complete enterprise CRM solution for JIL Pack. Includes: Lead Capture & Scoring, Sales Pipeline, AI Chatbot, Consultation Booking, Project Tracking, Workflow Automation, Analytics Dashboards, Unified Context MCP, and Sage 100 ERP bidirectional connector. Licensed under MPL-2.0 and GPL-3.0.',
    'author': 'JIL Pack',
    'website': 'https://www.jilpack.com',
    'depends': [
        'base', 'mail', 'contacts', 'sales_team', 'sale',
        'calendar', 'utm', 'account', 'web_editor',
    ],
    'data': [
        'security/jil_crm_security.xml',
        'security/ir.model.access.csv',
        'data/crm_stage_data.xml',
        'data/sequence_data.xml',
        'data/crm_lead_demo.xml',
        'data/bpmn_data.xml',
        'data/scoring_rule_data.xml',
        'data/workflow_data.xml',
        'data/chatbot_intent_data.xml',
        'data/kpi_data.xml',
        'data/cron_data.xml',
        'views/crm_lead_views.xml',
        'views/lead_scoring_views.xml',
        'views/lead_assignment_views.xml',
        'views/lead_capture_views.xml',
        'views/nurturing_views.xml',
        'views/booking_views.xml',
        'views/availability_views.xml',
        'views/chatbot_flow_views.xml',
        'views/chatbot_session_views.xml',
        'views/chatbot_intent_views.xml',
        'views/project_views.xml',
        'views/project_milestone_views.xml',
        'views/project_task_views.xml',
        'views/bpmn_views.xml',
        'views/claim_views.xml',
        'views/transport_views.xml',
        'views/recovery_views.xml',
        'views/support_views.xml',
        'views/workflow_views.xml',
        'views/email_sequence_views.xml',
        'views/notification_views.xml',
        'views/dashboard_views.xml',
        'views/kpi_views.xml',
        'views/context_mcp_views.xml',
        'views/context_governance_views.xml',
        'views/menu_views.xml',
        'report/crm_report.xml',
        'report/crm_report_templates.xml',
        'wizard/crm_lead_to_opportunity_views.xml',
        'wizard/crm_bulk_action_views.xml',
        'wizard/crm_lead_scoring_wizard_views.xml',
        'wizard/lead_assignment_wizard_views.xml',
        'wizard/crm_lead_lost_reason_wizard_views.xml',
        'security/sage_security.xml',
        'data/sage_data.xml',
        'views/sage_connector_views.xml',
    ],
    'demo': [],
    'icon': 'static/description/logo.png',
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'MPL-2.0',
}
