from . import crm_lead
from . import crm_stage
from . import res_partner
from . import lead_scoring
from . import lead_assignment
from . import lead_capture
from . import lead_nurturing
from . import deal_tracking
from . import chatbot_flow
from . import booking_calendar
from . import project_tracking
from . import workflow_automation
from . import email_sequence
from . import notification_trigger
from . import crm_dashboard
from . import context_mcp_core
from . import context_mcp_event
from . import context_ingestion
from . import context_sync
from . import context_governance
from . import bpmn_process
from . import claim
from . import transport
from . import recovery
from . import support_ticket
from . import sage_connector
